// Generated by generate_native_hook_methods.py; do not edit.
    void DrawInstanced(UINT VertexCountPerInstance,  UINT InstanceCount,  UINT StartVertexLocation,  UINT StartInstanceLocation) {
        Command([=](auto* p){p->DrawInstanced(VertexCountPerInstance, InstanceCount, StartVertexLocation, StartInstanceLocation);});
    }
    void DrawIndexedInstanced(UINT IndexCountPerInstance,  UINT InstanceCount,  UINT StartIndexLocation,  INT BaseVertexLocation,  UINT StartInstanceLocation) {
        Command([=](auto* p){p->DrawIndexedInstanced(IndexCountPerInstance, InstanceCount, StartIndexLocation, BaseVertexLocation, StartInstanceLocation);});
    }
    void Dispatch(UINT ThreadGroupCountX,  UINT ThreadGroupCountY,  UINT ThreadGroupCountZ) {
        Command([=](auto* p){p->Dispatch(ThreadGroupCountX, ThreadGroupCountY, ThreadGroupCountZ);});
    }
    void CopyBufferRegion(ID3D12Resource *pDstBuffer,  UINT64 DstOffset,  ID3D12Resource *pSrcBuffer,  UINT64 SrcOffset,  UINT64 NumBytes) {
        Keep(pDstBuffer);
        Keep(pSrcBuffer);
        Command([=](auto* p){p->CopyBufferRegion(pDstBuffer, DstOffset, pSrcBuffer, SrcOffset, NumBytes);});
    }
    void CopyTextureRegion(const D3D12_TEXTURE_COPY_LOCATION *pDst,  UINT DstX,  UINT DstY,  UINT DstZ,  const D3D12_TEXTURE_COPY_LOCATION *pSrc,  const D3D12_BOX *pSrcBox) {
        auto dst=*pDst,src=*pSrc;Keep(dst.pResource);Keep(src.pResource);
        const bool hasBox=pSrcBox!=nullptr;const auto box=hasBox?*pSrcBox:D3D12_BOX{};
        Command([=](auto* p){p->CopyTextureRegion(&dst, DstX, DstY, DstZ, &src, hasBox?&box:nullptr);});
    }
    void CopyResource(ID3D12Resource *pDstResource,  ID3D12Resource *pSrcResource) {
        Keep(pDstResource);
        Keep(pSrcResource);
        Command([=](auto* p){p->CopyResource(pDstResource, pSrcResource);});
    }
    void CopyTiles(ID3D12Resource *pTiledResource,  const D3D12_TILED_RESOURCE_COORDINATE *pTileRegionStartCoordinate,  const D3D12_TILE_REGION_SIZE *pTileRegionSize,  ID3D12Resource *pBuffer,  UINT64 BufferStartOffsetInBytes,  D3D12_TILE_COPY_FLAGS Flags) {
        Keep(pTiledResource);Keep(pBuffer);auto coordinate=*pTileRegionStartCoordinate;auto region=*pTileRegionSize;
        Command([=](auto* p){p->CopyTiles(pTiledResource, &coordinate, &region, pBuffer, BufferStartOffsetInBytes, Flags);});
    }
    void ResolveSubresource(ID3D12Resource *pDstResource,  UINT DstSubresource,  ID3D12Resource *pSrcResource,  UINT SrcSubresource,  DXGI_FORMAT Format) {
        Keep(pDstResource);
        Keep(pSrcResource);
        Command([=](auto* p){p->ResolveSubresource(pDstResource, DstSubresource, pSrcResource, SrcSubresource, Format);});
    }
    void IASetPrimitiveTopology(D3D12_PRIMITIVE_TOPOLOGY PrimitiveTopology) {
        State(20,0,[=](auto* p){p->IASetPrimitiveTopology(PrimitiveTopology);});
    }
    void RSSetViewports(UINT NumViewports,  const D3D12_VIEWPORT *pViewports) {
        auto copy1=Copy(static_cast<const D3D12_VIEWPORT*>(pViewports),NumViewports,16);
        State(21,0,[=](auto* p){p->RSSetViewports(NumViewports, copy1.empty()?nullptr:copy1.data());});
    }
    void RSSetScissorRects(UINT NumRects,  const D3D12_RECT *pRects) {
        auto copy1=Copy(static_cast<const D3D12_RECT*>(pRects),NumRects,16);
        State(22,0,[=](auto* p){p->RSSetScissorRects(NumRects, copy1.empty()?nullptr:copy1.data());});
    }
    void OMSetBlendFactor(const FLOAT BlendFactor[ 4 ]) {
        auto copy0=Copy(static_cast<const FLOAT*>(BlendFactor),4,4);
        State(23,0,[=](auto* p){p->OMSetBlendFactor(copy0.empty()?nullptr:copy0.data());});
    }
    void OMSetStencilRef(UINT StencilRef) {
        State(24,0,[=](auto* p){p->OMSetStencilRef(StencilRef);});
    }
    void SetPipelineState(ID3D12PipelineState *pPipelineState) {
        Keep(pPipelineState);
        State(25,0,[=](auto* p){p->SetPipelineState(pPipelineState);});
    }
    void SetComputeRootDescriptorTable(UINT RootParameterIndex,  D3D12_GPU_DESCRIPTOR_HANDLE BaseDescriptor) {
        Root(false,RootParameterIndex,1,[=](auto* p){p->SetComputeRootDescriptorTable(RootParameterIndex, BaseDescriptor);});
    }
    void SetGraphicsRootDescriptorTable(UINT RootParameterIndex,  D3D12_GPU_DESCRIPTOR_HANDLE BaseDescriptor) {
        Root(true,RootParameterIndex,1,[=](auto* p){p->SetGraphicsRootDescriptorTable(RootParameterIndex, BaseDescriptor);});
    }
    void SetComputeRoot32BitConstant(UINT RootParameterIndex,  UINT SrcData,  UINT DestOffsetIn32BitValues) {
        Root(false,RootParameterIndex,2,[=](auto* p){p->SetComputeRoot32BitConstant(RootParameterIndex, SrcData, DestOffsetIn32BitValues);},DestOffsetIn32BitValues);
    }
    void SetGraphicsRoot32BitConstant(UINT RootParameterIndex,  UINT SrcData,  UINT DestOffsetIn32BitValues) {
        Root(true,RootParameterIndex,2,[=](auto* p){p->SetGraphicsRoot32BitConstant(RootParameterIndex, SrcData, DestOffsetIn32BitValues);},DestOffsetIn32BitValues);
    }
    void SetComputeRoot32BitConstants(UINT RootParameterIndex,  UINT Num32BitValuesToSet,  const void *pSrcData,  UINT DestOffsetIn32BitValues) {
        if(RootParameterIndex>=64||DestOffsetIn32BitValues>64||Num32BitValuesToSet>64-DestOffsetIn32BitValues)throw std::runtime_error("root constant extent");
        auto copy=Copy(static_cast<const UINT*>(pSrcData),Num32BitValuesToSet,64);
        for(UINT i=0;i<Num32BitValuesToSet;++i){const auto value=copy[i],offset=DestOffsetIn32BitValues+i;
        Root(false,RootParameterIndex,2,[=](auto* p){p->SetComputeRoot32BitConstant(RootParameterIndex,value,offset);},offset);}
    }
    void SetGraphicsRoot32BitConstants(UINT RootParameterIndex,  UINT Num32BitValuesToSet,  const void *pSrcData,  UINT DestOffsetIn32BitValues) {
        if(RootParameterIndex>=64||DestOffsetIn32BitValues>64||Num32BitValuesToSet>64-DestOffsetIn32BitValues)throw std::runtime_error("root constant extent");
        auto copy=Copy(static_cast<const UINT*>(pSrcData),Num32BitValuesToSet,64);
        for(UINT i=0;i<Num32BitValuesToSet;++i){const auto value=copy[i],offset=DestOffsetIn32BitValues+i;
        Root(true,RootParameterIndex,2,[=](auto* p){p->SetGraphicsRoot32BitConstant(RootParameterIndex,value,offset);},offset);}
    }
    void SetComputeRootConstantBufferView(UINT RootParameterIndex,  D3D12_GPU_VIRTUAL_ADDRESS BufferLocation) {
        Root(false,RootParameterIndex,3,[=](auto* p){p->SetComputeRootConstantBufferView(RootParameterIndex, BufferLocation);});
    }
    void SetGraphicsRootConstantBufferView(UINT RootParameterIndex,  D3D12_GPU_VIRTUAL_ADDRESS BufferLocation) {
        Root(true,RootParameterIndex,3,[=](auto* p){p->SetGraphicsRootConstantBufferView(RootParameterIndex, BufferLocation);});
    }
    void SetComputeRootShaderResourceView(UINT RootParameterIndex,  D3D12_GPU_VIRTUAL_ADDRESS BufferLocation) {
        Root(false,RootParameterIndex,3,[=](auto* p){p->SetComputeRootShaderResourceView(RootParameterIndex, BufferLocation);});
    }
    void SetGraphicsRootShaderResourceView(UINT RootParameterIndex,  D3D12_GPU_VIRTUAL_ADDRESS BufferLocation) {
        Root(true,RootParameterIndex,3,[=](auto* p){p->SetGraphicsRootShaderResourceView(RootParameterIndex, BufferLocation);});
    }
    void SetComputeRootUnorderedAccessView(UINT RootParameterIndex,  D3D12_GPU_VIRTUAL_ADDRESS BufferLocation) {
        Root(false,RootParameterIndex,3,[=](auto* p){p->SetComputeRootUnorderedAccessView(RootParameterIndex, BufferLocation);});
    }
    void SetGraphicsRootUnorderedAccessView(UINT RootParameterIndex,  D3D12_GPU_VIRTUAL_ADDRESS BufferLocation) {
        Root(true,RootParameterIndex,3,[=](auto* p){p->SetGraphicsRootUnorderedAccessView(RootParameterIndex, BufferLocation);});
    }
    void IASetIndexBuffer(const D3D12_INDEX_BUFFER_VIEW *pView) {
        auto copy0=Copy(static_cast<const D3D12_INDEX_BUFFER_VIEW*>(pView),pView?1:0,1);
        State(43,0,[=](auto* p){p->IASetIndexBuffer(copy0.empty()?nullptr:copy0.data());});
    }
    void IASetVertexBuffers(UINT StartSlot,  UINT NumViews,  const D3D12_VERTEX_BUFFER_VIEW *pViews) {
        if(StartSlot>32||NumViews>32-StartSlot)throw std::runtime_error("binding extent");
        for(UINT i=0;i<NumViews;++i){const UINT index=StartSlot+i;const auto view=pViews?pViews[i]:D3D12_VERTEX_BUFFER_VIEW{};
        State(44,index,[=](auto* p){p->IASetVertexBuffers(index,1,&view);});}
    }
    void SOSetTargets(UINT StartSlot,  UINT NumViews,  const D3D12_STREAM_OUTPUT_BUFFER_VIEW *pViews) {
        if(StartSlot>4||NumViews>4-StartSlot)throw std::runtime_error("binding extent");
        for(UINT i=0;i<NumViews;++i){const UINT index=StartSlot+i;const auto view=pViews?pViews[i]:D3D12_STREAM_OUTPUT_BUFFER_VIEW{};
        State(45,index,[=](auto* p){p->SOSetTargets(index,1,&view);});}
    }
    void ClearDepthStencilView(D3D12_CPU_DESCRIPTOR_HANDLE DepthStencilView,  D3D12_CLEAR_FLAGS ClearFlags,  FLOAT Depth,  UINT8 Stencil,  UINT NumRects,  const D3D12_RECT *pRects) {
        const auto handle0=Descriptor(DepthStencilView,D3D12_DESCRIPTOR_HEAP_TYPE_DSV);
        auto copy5=Copy(static_cast<const D3D12_RECT*>(pRects),NumRects,65536);
        Command([=](auto* p){p->ClearDepthStencilView(handle0, ClearFlags, Depth, Stencil, NumRects, copy5.empty()?nullptr:copy5.data());});
    }
    void ClearRenderTargetView(D3D12_CPU_DESCRIPTOR_HANDLE RenderTargetView,  const FLOAT ColorRGBA[ 4 ],  UINT NumRects,  const D3D12_RECT *pRects) {
        const auto handle0=Descriptor(RenderTargetView,D3D12_DESCRIPTOR_HEAP_TYPE_RTV);
        auto copy1=Copy(static_cast<const FLOAT*>(ColorRGBA),4,4);
        auto copy3=Copy(static_cast<const D3D12_RECT*>(pRects),NumRects,65536);
        Command([=](auto* p){p->ClearRenderTargetView(handle0, copy1.empty()?nullptr:copy1.data(), NumRects, copy3.empty()?nullptr:copy3.data());});
    }
    void ClearUnorderedAccessViewUint(D3D12_GPU_DESCRIPTOR_HANDLE ViewGPUHandleInCurrentHeap,  D3D12_CPU_DESCRIPTOR_HANDLE ViewCPUHandle,  ID3D12Resource *pResource,  const UINT Values[ 4 ],  UINT NumRects,  const D3D12_RECT *pRects) {
        const auto handle1=Descriptor(ViewCPUHandle,D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);
        Keep(pResource);
        auto copy3=Copy(static_cast<const UINT*>(Values),4,4);
        auto copy5=Copy(static_cast<const D3D12_RECT*>(pRects),NumRects,65536);
        Command([=](auto* p){p->ClearUnorderedAccessViewUint(ViewGPUHandleInCurrentHeap, handle1, pResource, copy3.empty()?nullptr:copy3.data(), NumRects, copy5.empty()?nullptr:copy5.data());});
    }
    void ClearUnorderedAccessViewFloat(D3D12_GPU_DESCRIPTOR_HANDLE ViewGPUHandleInCurrentHeap,  D3D12_CPU_DESCRIPTOR_HANDLE ViewCPUHandle,  ID3D12Resource *pResource,  const FLOAT Values[ 4 ],  UINT NumRects,  const D3D12_RECT *pRects) {
        const auto handle1=Descriptor(ViewCPUHandle,D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);
        Keep(pResource);
        auto copy3=Copy(static_cast<const FLOAT*>(Values),4,4);
        auto copy5=Copy(static_cast<const D3D12_RECT*>(pRects),NumRects,65536);
        Command([=](auto* p){p->ClearUnorderedAccessViewFloat(ViewGPUHandleInCurrentHeap, handle1, pResource, copy3.empty()?nullptr:copy3.data(), NumRects, copy5.empty()?nullptr:copy5.data());});
    }
    void DiscardResource(ID3D12Resource *pResource,  const D3D12_DISCARD_REGION *pRegion) {
        Keep(pResource);const bool hasRegion=pRegion!=nullptr;auto region=hasRegion?*pRegion:D3D12_DISCARD_REGION{};
        auto rects=Copy(region.pRects,region.NumRects);
        Command([=](auto* p){auto local=region;local.pRects=rects.data();p->DiscardResource(pResource,hasRegion?&local:nullptr);});
    }
    void ResolveQueryData(ID3D12QueryHeap *pQueryHeap,  D3D12_QUERY_TYPE Type,  UINT StartIndex,  UINT NumQueries,  ID3D12Resource *pDestinationBuffer,  UINT64 AlignedDestinationBufferOffset) {
        Keep(pQueryHeap);
        Keep(pDestinationBuffer);
        Command([=](auto* p){p->ResolveQueryData(pQueryHeap, Type, StartIndex, NumQueries, pDestinationBuffer, AlignedDestinationBufferOffset);});
    }
    void SetMarker(UINT Metadata,  const void *pData,  UINT Size) {
        auto copy1=Copy(static_cast<const unsigned char*>(pData),Size,65536);
        Command([=](auto* p){p->SetMarker(Metadata, copy1.empty()?nullptr:copy1.data(), Size);});
    }
    void AtomicCopyBufferUINT(ID3D12Resource *pDstBuffer,  UINT64 DstOffset,  ID3D12Resource *pSrcBuffer,  UINT64 SrcOffset,  UINT Dependencies,  ID3D12Resource *const *ppDependentResources,  const D3D12_SUBRESOURCE_RANGE_UINT64 *pDependentSubresourceRanges) {
        (void)pDstBuffer;
        (void)DstOffset;
        (void)pSrcBuffer;
        (void)SrcOffset;
        (void)Dependencies;
        (void)ppDependentResources;
        (void)pDependentSubresourceRanges;
        Reject("AtomicCopyBufferUINT requires qualification");
    }
    void AtomicCopyBufferUINT64(ID3D12Resource *pDstBuffer,  UINT64 DstOffset,  ID3D12Resource *pSrcBuffer,  UINT64 SrcOffset,  UINT Dependencies,  ID3D12Resource *const *ppDependentResources,  const D3D12_SUBRESOURCE_RANGE_UINT64 *pDependentSubresourceRanges) {
        (void)pDstBuffer;
        (void)DstOffset;
        (void)pSrcBuffer;
        (void)SrcOffset;
        (void)Dependencies;
        (void)ppDependentResources;
        (void)pDependentSubresourceRanges;
        Reject("AtomicCopyBufferUINT64 requires qualification");
    }
    void OMSetDepthBounds(FLOAT Min,  FLOAT Max) {
        State(62,0,[=](auto* p){Extended<ID3D12GraphicsCommandList1>(p,[&](auto* x){x->OMSetDepthBounds(Min, Max);});});
    }
    void SetSamplePositions(UINT NumSamplesPerPixel,  UINT NumPixels,  D3D12_SAMPLE_POSITION *pSamplePositions) {
        (void)NumSamplesPerPixel;
        (void)NumPixels;
        (void)pSamplePositions;
        Reject("SetSamplePositions requires qualification");
    }
    void ResolveSubresourceRegion(ID3D12Resource *pDstResource,  UINT DstSubresource,  UINT DstX,  UINT DstY,  ID3D12Resource *pSrcResource,  UINT SrcSubresource,  D3D12_RECT *pSrcRect,  DXGI_FORMAT Format,  D3D12_RESOLVE_MODE ResolveMode) {
        Keep(pDstResource);
        Keep(pSrcResource);
        auto copy6=Copy(static_cast<const D3D12_RECT*>(pSrcRect),pSrcRect?1:0,1);
        Command([=](auto* p) mutable{Extended<ID3D12GraphicsCommandList1>(p,[&](auto* x){x->ResolveSubresourceRegion(pDstResource, DstSubresource, DstX, DstY, pSrcResource, SrcSubresource, copy6.empty()?nullptr:copy6.data(), Format, ResolveMode);});});
    }
    void SetViewInstanceMask(UINT Mask) {
        State(65,0,[=](auto* p){Extended<ID3D12GraphicsCommandList1>(p,[&](auto* x){x->SetViewInstanceMask(Mask);});});
    }
    void WriteBufferImmediate(UINT Count,  const D3D12_WRITEBUFFERIMMEDIATE_PARAMETER *pParams,  const D3D12_WRITEBUFFERIMMEDIATE_MODE *pModes) {
        // This is an ordered GPU write, not persistent command-list state. Keep
        // both caller-owned arrays until the prefix/suffix list is recorded.
        // A null pModes means DEFAULT for every write and must stay null.
        auto params = Copy(pParams, Count);
        const bool hasModes = pModes != nullptr;
        auto modes = Copy(pModes, hasModes ? Count : 0);
        Command([=](auto* p) {
            Extended<ID3D12GraphicsCommandList2>(p, [&](auto* list) {
                list->WriteBufferImmediate(Count, params.empty() ? nullptr : params.data(),
                                           hasModes ? modes.data() : nullptr);
            });
        });
    }
    void SetProtectedResourceSession(ID3D12ProtectedResourceSession *pProtectedResourceSession) {
        (void)pProtectedResourceSession;
        Reject("SetProtectedResourceSession requires qualification");
    }
    void BeginRenderPass(UINT NumRenderTargets,  const D3D12_RENDER_PASS_RENDER_TARGET_DESC *pRenderTargets,  const D3D12_RENDER_PASS_DEPTH_STENCIL_DESC *pDepthStencil,  D3D12_RENDER_PASS_FLAGS Flags) {
        (void)NumRenderTargets;
        (void)pRenderTargets;
        (void)pDepthStencil;
        (void)Flags;
        Reject("BeginRenderPass requires qualification");
    }
    void EndRenderPass() {
        Reject("EndRenderPass requires qualification");
    }
    void InitializeMetaCommand(ID3D12MetaCommand *pMetaCommand,  const void *pInitializationParametersData,  SIZE_T InitializationParametersDataSizeInBytes) {
        (void)pMetaCommand;
        (void)pInitializationParametersData;
        (void)InitializationParametersDataSizeInBytes;
        Reject("InitializeMetaCommand requires qualification");
    }
    void ExecuteMetaCommand(ID3D12MetaCommand *pMetaCommand,  const void *pExecutionParametersData,  SIZE_T ExecutionParametersDataSizeInBytes) {
        (void)pMetaCommand;
        (void)pExecutionParametersData;
        (void)ExecutionParametersDataSizeInBytes;
        Reject("ExecuteMetaCommand requires qualification");
    }
    void BuildRaytracingAccelerationStructure(const D3D12_BUILD_RAYTRACING_ACCELERATION_STRUCTURE_DESC *pDesc,  UINT NumPostbuildInfoDescs,  const D3D12_RAYTRACING_ACCELERATION_STRUCTURE_POSTBUILD_INFO_DESC *pPostbuildInfoDescs) {
        (void)pDesc;
        (void)NumPostbuildInfoDescs;
        (void)pPostbuildInfoDescs;
        Reject("BuildRaytracingAccelerationStructure requires qualification");
    }
    void EmitRaytracingAccelerationStructurePostbuildInfo(const D3D12_RAYTRACING_ACCELERATION_STRUCTURE_POSTBUILD_INFO_DESC *pDesc,  UINT NumSourceAccelerationStructures,  const D3D12_GPU_VIRTUAL_ADDRESS *pSourceAccelerationStructureData) {
        (void)pDesc;
        (void)NumSourceAccelerationStructures;
        (void)pSourceAccelerationStructureData;
        Reject("EmitRaytracingAccelerationStructurePostbuildInfo requires qualification");
    }
    void CopyRaytracingAccelerationStructure(D3D12_GPU_VIRTUAL_ADDRESS DestAccelerationStructureData,  D3D12_GPU_VIRTUAL_ADDRESS SourceAccelerationStructureData,  D3D12_RAYTRACING_ACCELERATION_STRUCTURE_COPY_MODE Mode) {
        (void)DestAccelerationStructureData;
        (void)SourceAccelerationStructureData;
        (void)Mode;
        Reject("CopyRaytracingAccelerationStructure requires qualification");
    }
    void SetPipelineState1(ID3D12StateObject *pStateObject) {
        (void)pStateObject;
        Reject("SetPipelineState1 requires qualification");
    }
    void DispatchRays(const D3D12_DISPATCH_RAYS_DESC *pDesc) {
        (void)pDesc;
        Reject("DispatchRays requires qualification");
    }
    void RSSetShadingRate(D3D12_SHADING_RATE baseShadingRate,  const D3D12_SHADING_RATE_COMBINER *combiners) {
        (void)baseShadingRate;
        (void)combiners;
        Reject("RSSetShadingRate requires qualification");
    }
    void RSSetShadingRateImage(ID3D12Resource *shadingRateImage) {
        (void)shadingRateImage;
        Reject("RSSetShadingRateImage requires qualification");
    }
    void DispatchMesh(UINT ThreadGroupCountX,  UINT ThreadGroupCountY,  UINT ThreadGroupCountZ) {
        (void)ThreadGroupCountX;
        (void)ThreadGroupCountY;
        (void)ThreadGroupCountZ;
        Reject("DispatchMesh requires qualification");
    }
    void Barrier(UINT32 NumBarrierGroups,  const D3D12_BARRIER_GROUP *pBarrierGroups) {
        (void)NumBarrierGroups;
        (void)pBarrierGroups;
        Reject("Barrier requires qualification");
    }
    void OMSetFrontAndBackStencilRef(UINT FrontStencilRef,  UINT BackStencilRef) {
        (void)FrontStencilRef;
        (void)BackStencilRef;
        Reject("OMSetFrontAndBackStencilRef requires qualification");
    }
    void RSSetDepthBias(FLOAT DepthBias,  FLOAT DepthBiasClamp,  FLOAT SlopeScaledDepthBias) {
        (void)DepthBias;
        (void)DepthBiasClamp;
        (void)SlopeScaledDepthBias;
        Reject("RSSetDepthBias requires qualification");
    }
    void IASetIndexBufferStripCutValue(D3D12_INDEX_BUFFER_STRIP_CUT_VALUE IBStripCutValue) {
        (void)IBStripCutValue;
        Reject("IASetIndexBufferStripCutValue requires qualification");
    }
    void SetProgram(const D3D12_SET_PROGRAM_DESC *pDesc) {
        (void)pDesc;
        Reject("SetProgram requires qualification");
    }
    void DispatchGraph(const D3D12_DISPATCH_GRAPH_DESC *pDesc) {
        (void)pDesc;
        Reject("DispatchGraph requires qualification");
    }
